{% set dataset_name = "PhotonEvaporation" %}
{% set version = "5.7" %}
{% set env_var = "G4LEVELGAMMADATA" %}
{% set summary = "GEANT4 data files for photon evaporation" %}

{% set name = "geant4-data-"+dataset_name.lower() %}
{% set install_dir = "share/Geant4/data/"+dataset_name+version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://geant4-data.web.cern.ch/geant4-data/datasets/G4{{ dataset_name }}.{{ version }}.tar.gz
  sha256: 4fe8d7400d6461b9bfec27c4a1867c4b7df60581ab9feaf2bbdee924e8bcb4cc
  folder: dataset

build:
  number: 1
  noarch: generic
  script:
    - mkdir -p ${PREFIX}/{{ install_dir }}
    - cp -r dataset/* ${PREFIX}/{{ install_dir }}
    - ${RECIPE_DIR}/create_activation_scripts.sh {{ name }} {{ env_var }} {{ install_dir }}

# Conda-forge is unable to build packages that have no dependencies so add
# `make` as a dummy build dependency
requirements:
  build:
    - make

test:
  commands:
    - '[ "${{ env_var }}" == "$CONDA_PREFIX/{{ install_dir }}" ]'

about:
  home: https://geant4.web.cern.ch/
  summary: {{ summary }}
  license: OTHER
  license_file: CREDIT

extra:
  recipe-maintainers:
    - chrisburr
    - tkittel
